# Copyright (c) 2025 Planet Innovation Pty Ltd
# SPDX-License-Identifier: MIT

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - quality
  - test
  - docs

image: ${CI_REGISTRY}/degraves/micropython_build_env_docker

checks:
  image: ${CI_REGISTRY}/degraves/ci/pre-commit-base:v0.0.2
  stage: quality
  tags: ["aws-525-degraves"]
  script:
    - pre-commit run --all-files --show-diff-on-failure

unit_test:
  image: ${CI_REGISTRY}/degraves/ci/micropython-unix-unittest:latest
  stage: test
  tags: ["aws-525-degraves"]
  needs: []
  script:
    - make tests
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - results/*.xml

.docs:
  image: python:3.11-slim
  stage: docs
  tags: ["aws-525-degraves"]
  before_script:
    - pip install -r requirements-docs.txt
  script:
    - mkdocs build --site-dir ./public

pages:
  extends: .docs
  artifacts:
    paths:
      - public
  only:
    - main

pages-mr:
  extends: .docs
  artifacts:
    paths:
      - public
    expire_in: 1 week
  variables:
      PUBLIC_URL: "$CI_PAGES_URL/../../-/library/micropython-mock-machine/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  environment:
      name: review/$CI_COMMIT_REF_NAME
      url: "$CI_PAGES_URL/../../-/library/micropython-mock-machine/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  only:
    - merge_requests
