#   PI Background IP
#   Copyright (c) 2022, Planet Innovation
#   436 Elgar Road, Box Hill VIC 3128 Australia
#   Phone: +61 3 9945 7510
#
#   The copyright to the computer program(s) herein is the property of
#   Planet Innovation, Australia.
#   The program(s) may be used and/or copied only with the written permission
#   of Planet Innovation or in accordance with the terms and conditions
#   stipulated in the agreement/contract under which the program(s) have been
#   supplied.

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - quality
  - test

image: ${CI_REGISTRY}/degraves/micropython_build_env_docker

checks:
  image: ${CI_REGISTRY}/degraves/ci/pre-commit-base:v0.0.2
  stage: quality
  tags: ["aws-525-degraves"]
  script:
    - pre-commit run --all-files --show-diff-on-failure

unit_test:
  image: ${CI_REGISTRY}/degraves/ci/micropython-unix-unittest:latest
  stage: test
  tags: ["aws-525-degraves"]
  needs: []
  script:
    - make tests
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - results/*.xml
